version: '3.8'  

services:  
  frontend:  
    build: ./frontend  
    ports:  
      - "8080:80"  
    
  api:  
    build: ./api  
    ports:  
      - "5000:5000"  
    
  database:  
    image: postgres  
    environment:  
      POSTGRES_DB: mydb  
      POSTGRES_USER: myuser  
      POSTGRES_PASSWORD: mypassword  
    volumes:  
      - db_data:/var/lib/postgresql/data  

volumes:  
  db_data:
